# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-11 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, default='en', max_length=2)),
                ('languages', models.CharField(blank=True, default='en', max_length=300)),
                ('languages_force', models.CharField(blank=True, default='en', max_length=300)),
                ('ocr', models.BooleanField(default=True)),
                ('ocr_languages', models.CharField(blank=True, default='en', max_length=300)),
                ('ocr_descew', models.BooleanField(default=False)),
                ('ocr_pdf', models.BooleanField(default=True)),
                ('ner_spacy', models.BooleanField(default=True)),
                ('ner_stanford', models.BooleanField(default=False)),
            ],
        ),
    ]
