# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='graph_neo4j',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='graph_neo4j_browser',
            field=models.CharField(blank=True, default='http://localhost:7474/browser/', max_length=1000),
        ),
        migrations.AddField(
            model_name='setup',
            name='graph_neo4j_host',
            field=models.CharField(blank=True, default='localhost', max_length=1000),
        ),
        migrations.AddField(
            model_name='setup',
            name='graph_neo4j_password',
            field=models.CharField(blank=True, default='neo4j', max_length=1000),
        ),
        migrations.AddField(
            model_name='setup',
            name='graph_neo4j_user',
            field=models.CharField(blank=True, default='neo4j', max_length=1000),
        ),
    ]
