# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-03 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_segmentation_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='languages_force_hunspell',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='setup',
            name='languages_hunspell',
            field=models.CharField(blank=True, default='hu', max_length=300),
        ),
	migrations.RunSQL("UPDATE setup_setup SET languages_hunspell='hu'"),
	migrations.RunSQL("UPDATE setup_setup SET languages_force_hunspell=''"),
    ]
