# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-28 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_segmentation_pages_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='segmentation_sentences',
            field=models.BooleanField(default=False),
        ),
    ]
