# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-18 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_segmentation_sentences'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='ocr_later',
            field=models.BooleanField(default=True),
        ),
    ]
