# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_ocr_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='url_tasks',
            field=models.CharField(blank=True, default='http://localhost:5555', max_length=1000),
        ),
    ]
