# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-31 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0002_auto_20171106_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ontologies',
            name='do_stemming',
        ),
        migrations.AddField(
            model_name='ontologies',
            name='stemming',
            field=models.CharField(blank=True, default='en', max_length=300),
        ),
        migrations.AddField(
            model_name='ontologies',
            name='stemming_force',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='ontologies',
            name='stemming_force_hunspell',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='ontologies',
            name='stemming_hunspell',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
