# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0007_dynamic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='facet',
            name='graph_enabled',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facet',
            name='graph_limit',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='facet',
            name='style_color',
            field=models.CharField(blank=True, default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='facet',
            name='style_color_background',
            field=models.CharField(blank=True, default='lightgray', max_length=20),
        ),

        migrations.RunSQL("UPDATE thesaurus_facet SET style_color_background='#f9ebdd' WHERE facet='person_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET style_color_background='#eaf9d5' WHERE facet='organization_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET style_color_background='#e3ebf9' WHERE facet='location_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET style_color_background='lightblue' WHERE facet='hashtag_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET style_color_background='orange' WHERE facet='author_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET style_color_background='cyan' WHERE facet='email_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET graph_enabled=0 WHERE facet='content_type_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET graph_enabled=0 WHERE facet='content_type_group_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET graph_enabled=0 WHERE facet='language_s'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET graph_enabled=0 WHERE facet='money_ss'"),
        migrations.RunSQL("UPDATE thesaurus_facet SET graph_enabled=0 WHERE facet='hashtag_ss'"),

    ]
