# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0008_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='facet',
            name='closed',
            field=models.NullBooleanField(default=False),
        ),
    ]
