#!/bin/sh
# postinst script for webapps

# install django-import-export
pip3 install django-import-export

# export static files to directory for webserver
python3 /var/lib/opensemanticsearch/manage.py collectstatic --noinput

# create or upgrade DB
python3 /var/lib/opensemanticsearch/manage.py migrate

# create directory for file uploads
mkdir /var/opensemanticsearch
chown www-data:www-data /var/opensemanticsearch

# allow Django running in apache2 context to read and write to DB
chgrp www-data /var/lib/opensemanticsearch
chmod g+w /var/lib/opensemanticsearch
chmod -R g+r /var/lib/opensemanticsearch
chown www-data:www-data /var/lib/opensemanticsearch/db.sqlite3

# but others should not be able to read DB entries
chmod o-r /var/lib/opensemanticsearch/db.sqlite3

# allow Django running in apache2 context to write facets config
chgrp www-data /etc/opensemanticsearch/facets
chmod g+r /etc/opensemanticsearch/facets
chmod g+w /etc/opensemanticsearch/facets

# allow Django running in apache2 context to write ETL config
chgrp www-data /etc/opensemanticsearch/etl-webadmin
chmod g+r /etc/opensemanticsearch/etl-webadmin
chmod g+w /etc/opensemanticsearch/etl-webadmin

# allow Django running in apache2 context to write UI config
chgrp www-data /etc/solr-php-ui/config.webadmin.php
chmod g+r /etc/solr-php-ui/config.webadmin.php
chmod g+w /etc/solr-php-ui/config.webadmin.php

# enable apache2 module for Django
a2enmod wsgi

# reload apache configs to enable our additional apache settings
service apache2 restart

# setup facets/classes in Open Semantic ETL and entities in Open Semantic Search API
python3 /var/lib/opensemanticsearch/manage.py entities

# allow Django running in apache2 context to write OCR dictionary
chown www-data:www-data /etc/opensemanticsearch/ocr/dictionary.txt
chmod o+r /etc/opensemanticsearch/ocr/dictionary.txt

# set rights of cron table
chown root:root /etc/cron.d/open-semantic-search

# load our cron table
service cron restart

exit 0
