# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypothesis', '0002_auto_20180227_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypothesis',
            name='user',
            field=models.CharField(blank=True, default='opensemanticsearch', max_length=1000),
        ),
    ]
